[project]
name = "tt6581-verilator-sim"
version = "1.0.0"
description = "Python environment for parsing Verilator testbench output for TT6581."
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "scipy>=1.17.1",
]
