name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Install verilator
        uses: veryl-lang/setup-verilator@v1
        with:
          verilator-version: v5.040

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: |
          cd test
          make clean
          SIM=verilator make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()
      
      - name: Push plots to artifact branch
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p plots_deploy
          cd plots_deploy
          git init
          git checkout --orphan test-artifacts

          mkdir -p tmp
          cp ../test/tmp/*.png ./tmp/ || true

          git add tmp/
          git commit -m "Update test plots for run ${{ github.run_id }} [skip ci]" || true
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git test-artifacts

      - name: Generate test summary with plots
        if: always()
        run: python test/gen_summary.py

      - name: upload waveform and test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test/results.xml
            test/tmp/*
